# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DemoYummie' do
	pod 'XLForm', '~> 3.0.0'
	pod 'JVFloatLabeledTextField', '1.1.0', :inhibit_warnings => true
	pod "AFNetworking", "~> 2.0"
end

target 'DemoYummieTests' do

end

